name: CI/CD Nginx Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'docker/index.html'  # Solo se ejecuta si cambia el index.html

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y etiquetar la imagen
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-cicd:latest .

      - name: Subir imagen a Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx-cicd:latest

      - name: Detener y eliminar contenedor
        run: |
          docker stop ci-cd-nginx:latest || true
          docker rm ci-cd-nginx:latest || true
      - name: Descargar nueva imagen
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/nginx-cicd:latest

      - name: Ejecutar nuevo contenedor
        run: |
          docker run -d --name nginx_container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/nginx-cicd:latest
